### ISSUE TITLE
Pattern

### ISSUE THREAD

**Issue by RobTF9** [bristol-tech-fair/btf-frontend#24]
Create the pattern component.

[View on figma](https://www.figma.com/file/gGwSe7ilZCUmAIaJyUc4iY/Bristol-Tech-Fair-Design-System?node-id=289%3A89)

**Comment by admtomas** [comment]
Just qick question. Inside Pattern component code i see `dangerouslySetInnerHTML`, its classified as unsafe as  it open the doors to XSS attacks. So question  is it safe for feeding images?
