### ISSUE TITLE
Build app router

### ISSUE THREAD

**Issue by RobTF9** [bristol-tech-fair/btf-frontend#41]
We need to build out the touring for application.

Diagram here: https://www.figma.com/file/gGwSe7ilZCUmAIaJyUc4iY/Bristol-Tech-Fair-Design-System?node-id=470%3A0

I've already installed react-router-dom, but feel free to use something else.

Assign yourself if you're interested in working on this.

**Comment by mburridge** [comment]
I'm interested in being involved with this. I've tried to do some routing previously, but would like to learn more about this.

**Comment by EdFildes** [comment]
Happy to help out with this too

**Comment by mmkobylin** [comment]
I have done some routing previously, but I would like to learn more about architecture of the site?

**Comment by r1903** [comment]
I have added basic routing for the app. Still a lot of work is there, please have a look and add or modify a code if necessary. 

You can find changes in branch 'feature/router'.
