### ISSUE TITLE
Spec the remaining components on the site.

### ISSUE THREAD

**Issue by RobTF9** [bristol-tech-fair/btf-frontend#42]
I need some assitance standardising and specing the remaining components, any one who's interested please assign yourself to this and we can have a follow up.

**Comment by EdFildes** [comment]
Happy to help out with this

**Comment by dwyafon** [comment]
I've never built up the routing for an app before, but I'm happy to throw myself into this issue and work/learn alongside others.

**Comment by RobTF9** [comment]
@EdFildes @shanesc Have either of you got any experience using design software i.e. Figma?

**Comment by shanesc** [comment]
Not really any experience for me, but something I've been wanting to learn. Happy to do a Youtube crash course if you think it would help.

**Comment by EdFildes** [comment]
@RobTF9 I have a tiny amount of experience with Adobe XD, thats about it. Keen to learn though.
