### ISSUE TITLE
Workout media queries we need from figma file.

### ISSUE THREAD

**Issue by RobTF9** [bristol-tech-fair/btf-frontend#43]

**Comment by dwyafon** [comment]
I'll have a look at the Figma file and add questions here.

**Comment by RobTF9** [comment]
Perfect, thank you! :)

**Comment by dwyafon** [comment]
@RobTF9  

My questions: 

- Will media queries be used only for layout changes?
- How do you want the breakpoints to be available to each 'page' and component? For example, I could set up a 'media-helper' file that reduces minimum widths to a set of variables (extraSmall, small, medium, large, extraLarge) that others can import and use accordingly in the their respective styling
- What do you recommend as the best first steps for determining the media queries without having full pages mocked up?
- Will more wireframes be added to the Figma file showing complete page layouts?

**Comment by RobTF9** [comment]
1. Yes, only using media queries for responsive layout changes.
2. A Javascript helper function that returns the media query as a string would be the best way to approach this. That way we can inject it into the styled components.
3. We're only using styled components.
4. The full pages are mocked up here: https://www.figma.com/file/gGwSe7ilZCUmAIaJyUc4iY/Bristol-Tech-Fair--Design-System?node-id=305%3A280
5. She has defined the sizes for the media queries, take a look at the different widths on the page above. I also defined them (here)[https://github.com/bristol-tech-fair/btf-frontend/blob/develop/src/theme/typography.styles.js]. Just need to develop a re-usable system to sahre them with other components.

**Comment by dwyafon** [comment]
@RobTF9 

In which directory is the helper function meant to reside?

**Comment by RobTF9** [comment]
Put it in the `src/utils` directory
