### ISSUE TITLE
LoveIllustration

### ISSUE THREAD

**Issue by RobTF9** [bristol-tech-fair/btf-frontend#45]
Import LoveIllustration as component from Figma.

https://www.figma.com/file/gGwSe7ilZCUmAIaJyUc4iY/Bristol-Tech-Fair-Design-System?node-id=524%3A3174

**Comment by admtomas** [comment]
Hey Marta. I just updated new Robot component. Please have a look and share your opinion. And how you doing with your part?  PS. look at issues regarding colors. Thanks.

**Comment by mmkobylin** [comment]
thanks Tomasz, I am playing around with CSS and creating letter designs. Some of this stuff is fairly new for me, so if I will get stuck I will give more experience guys a shout! And thanks for the info with the colours.

**Comment by mmkobylin** [comment]
@admtomas hi  Tomasz, quick question. I have copied and pasted all the svg paths, but the items do not seem to be falling into right places ( they are all squished in a left top corner). How do I position them correctly?

**Comment by admtomas** [comment]
> 
> 
> @admtomas hi Tomasz, quick question. I have copied and pasted all the svg paths, but the items do not seem to be falling into right places ( they are all squished in a left top corner). How do I position them correctly?

I did pull request and marked code whitch is conflicting. Please have a look. Let me know if you need more info.

**Comment by mmkobylin** [comment]
@admtomas thank you, but I don't seem to be able to fins marking. Any chance you could leave a comment on the part of the code? Thanks!

**Comment by admtomas** [comment]
Ah ok. Do as follow. Go to branches and click at Pull request by yourself of the component you making. I will be able to mark it down now for you, i think it was visible just for me when i did it. Second part message me on slack as it will be easier to me to leve more comments for you.

**Comment by admtomas** [comment]
Main problem with your code is that you have nested SVG inside SVG.  My advice is to rename your "LoveIllustrationWrapper" to "SVG". This way you will know what it is for. Then check the  SVG on figma. Yours is wrong.
Your structure should be sth like that:
```
 `const Love = () => {
  return (
    <SVG>
<title>Image of a sign</title>
<desc>Blue and pink sign with a word love.</desc>
<path />
<SVG>
);};
export default Love;`
```
`<title> & <desc>` are for accessibility and are similar to "alt" atribute. Think about diference of my example and yours if you were a blind person using screen reader.

**Comment by admtomas** [comment]
Marta i pushed mine and Eddies images to your branch. Before you start working use command: .....git pull....
and update all files on your computer.
Please do not delete them. Finish your image and our components are done.
Thx

**Comment by mmkobylin** [comment]
Git pull successful. Turns out the issue with the spacing was that I was pulling each path one by one instead of taking it all from the top. I have finished the image now, and I am waiting for review. Thanks!

**Comment by admtomas** [comment]
All ok. I just cleaned some bits. I changed IDs as we all had diferent across all 3 images, now its the same. I removed some files we dont need at all, its empty component you have on your computer. Double check. Just pull github version again for update  and check how it all working:)
