### ISSUE TITLE
We have 4th color blue used in new Robot illustrations

### ISSUE THREAD

**Issue by admtomas** [bristol-tech-fair/btf-frontend#50]
#36A9E1 is  used in new Robot designs.
If possible i would like to ask Shane to add it to the palette as:

`:root {
...
--greyblue: #36A9E1;
}
`

**Comment by shanesc** [comment]
Hi Tomasz,

Good catch on the colors, but just looking at how similar they are can they not just be the same? I can't really tell from the Figma components if it's the design intent or not. Maybe one for Marija to answer?

![image](https://user-images.githubusercontent.com/47223963/106395280-4de82c80-63f9-11eb-84eb-5a993771a37e.png)
