### ISSUE TITLE
Add global style for input components

### ISSUE THREAD

**Issue by catherinehoward** [bristol-tech-fair/btf-frontend#56]
Do we need to create global style for the input, select & textarea?
Update init.styles.js with the following:

input, 
textarea, select {
	padding: var(--small-space) var(--smallest-space);
        border: 0.1rem solid var(--lightblue);
        background: var(--lightgrey);
        border-radius: 0.5rem;
}

placeholder {
       color: var(--darkgrey);
       font-size: 1rem;
}

**Comment by admtomas** [comment]
Looking, maybe bit ahead, at some designs some attributes mentioned above are different. Correct me if i am wrong.

**Comment by vixhez** [comment]
Hey Catherine,

This looks great, thank you for putting it together.

Comparing it to the select styling I currently have, the only difference is my border radius, so perhaps we could designate that property individually along with any other unique ones? As well as anything else different Tumeka may have.

**Comment by catherinehoward** [comment]
Hi Victoria, yes I noticed your border-radius was different. Should've flagged it up. I checked the Figma design and the border-radius for all the inputs is 5px. 1 rem = 10px ( the font-size of the root element <html> is 10px - see src\theme\init.styles.js) so 0.5rem is 5px. Think that's right!

@admtomas where did you spot the differences? Was it one of the template designs? I'll have a look.

**Comment by admtomas** [comment]
> 
> 
> Hi Victoria, yes I noticed your border-radius was different. Should've flagged it up. I checked the Figma design and the border-radius for all the inputs is 5px. 1 rem = 10px ( the font-size of the root element is 10px - see src\theme\init.styles.js) so 0.5rem is 5px. Think that's right!
> 
> @admtomas where did you spot the differences? Was it one of the template designs? I'll have a look.

Maybe i look at it bit ahead but yes it is inside working templates. Look at "Submit Resource form" or "Filter". Initially we have diferent border color and "no border" at all. If thats how it is going to look, then when you set up global style as given example above, then we might have to add new style later or you could set all need styling on respective components now.
That could be in form of props . 
`border: ${(props) => (props.color ? '0.1rem solid #BF3459 : '0.1rem solid var(--lightblue)')}; `

When we call components we simply do sth like that `<Input color />` and you will have input with diferent border color.

Just check and corect me if i am wrong:)

**Comment by vixhez** [comment]
Ah, I see. Great, thank you for that Catherine. Are you happy to put that into the global styles folder, and then it will target all 3 of the components once everything is approved and on everyone's machine? Otherwise I'm happy to.

That could be worth discussing on Wednesday Tomasz, thanks for that!

**Comment by catherinehoward** [comment]
Hi Victoria, yes I'll add those changes to the global styles folder.

**Comment by vixhez** [comment]
Sounds great. Thanks!
