### ISSUE TITLE
Globalstyle is kicking at diferent breakpoints?

### ISSUE THREAD

**Issue by admtomas** [bristol-tech-fair/btf-frontend#74]
May i ask for verification when mediaquerys are kicking in.  We have 600px and 1024px in global styles but for some reason on my PC they kick in at 840px and 1260px. I noticed it on headers.Thx.

**Comment by r1903** [comment]
I have checked it, and it is working fine for me. Could you please mention a particular example where it is not working?

**Comment by admtomas** [comment]
While i was testing the component (resource Card or now Footer) i use Responsive Design Mode in Firefox. I am testing it in Storybook mode . I am just wondering if the breakpoints do not kick in corectly beacuse of the Left side panel in Story mode is taking first 200 pixels and its just annoying glitch. Beacuse when i set manualy resoultion to 600px, media kick-in for a second then disapear.
If that is the truth the there is no problem with mediaQuerys.
btw thx for checking it.

**Comment by r1903** [comment]
I am using chrome, and it works fine.  

Just for your information, Story book itself has the option to select a different screen size (you can customize viewport). I hope you are using the same thing to test.

**Comment by admtomas** [comment]
I am closing left sidebar and using "Docs" mode in Storybook for testing. 
All is fine now as i said earlier i had some glitches. Thanks for checkin it up for me.

**Comment by admtomas** [comment]
All is sorted now. Thanks for checking it up for me.
