### ISSUE TITLE
PostCard

### ISSUE THREAD

**Issue by catherinehoward** [bristol-tech-fair/btf-frontend#93]
Create a Post card component. 

[Design in Figma](https://www.figma.com/file/gGwSe7ilZCUmAIaJyUc4iY/Bristol-Tech-Fair-Design-System?node-id=448%3A1835)

![image](https://user-images.githubusercontent.com/51328026/117572944-3641d380-b0cd-11eb-90c9-b3a41ac0e4e4.png)

**Comment by admtomas** [comment]
Before merge please see coment in Pull request. Please Update branch with develop before Merge, [https://stackoverflow.com/questions/3876977/update-git-branches-from-master](url)
